<?php
add_action( 'wp_enqueue_scripts', 'vue_enqueue_spa_scripts' );
function vue_enqueue_spa_scripts() {
		// register the Vue build script.
		wp_register_script( // the app build script generated by Webpack.
			'app',
			'http://localhost:8843/dist/build.js',
			array(),
			false,
			true
		);
           
    		// enqueue the Vue app script with localized data.
		wp_enqueue_script( 'app' );
}