<?php
function vue_enqueue_spa_scripts() {
		// register the Vue build script.
		wp_register_script( // the app build script generated by Webpack.
			'app',
			'http://localhost:8843/dist/build.js',
			array(),
			false,
			true
		);
           
    		// enqueue the Vue app script with localized data.
		wp_enqueue_script( 'app' );
}
function gulp_enqueue_scripts(){
	wp_register_script(
		'my-scripts',
		get_template_directory_uri() . '/assets/js/App.js',
		array(),
		true 
	);
}